# Generated by Django 3.0.4 on 2020-04-19 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address1', models.CharField(max_length=120, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('pl', 'Poland'), ('ua', 'Ukraine'), ('us', 'USA')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
