# Generated by Django 3.0.6 on 2020-05-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_update',
            new_name='date_updated',
        ),
    ]
